# Generated by Django 5.2.13 on 2026-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='running', max_length=20),
        ),
    ]
